### ISSUE TITLE
Can not get AccessibleJvm List

### ISSUE THREAD

**Issue by stone89son** [google/access-bridge-explorer#13]
I cloned source code from GitHub run is ok,its can view panel, viewport,property...

I create new project and add code line:

```
AccessBridge accessBridge = new AccessBridge();
accessBridge.Initialize();
List<AccessibleJvm> lstAccessibleJvm= accessBridge.EnumJvms();

```

But lstAccessibleJvm aways is count =0.

**Comment by nguyenngocanh94** [comment]
cause of the `AccessBridge` need a  windows message pump. so try to init java access bridge in a window. then the jab should work.
