### ISSUE TITLE
"find Accessibility element using mouse pointer" gives wrong element.

### ISSUE THREAD

**Issue by BalarajAdappa** [google/access-bridge-explorer#21]
Hi everyone ,
 I'm  trying to spy element from mouse but elements  appearing at wrong screen coordinates.
as shown below window coordinates not relevant to screen.

help would appreciated.
thanks .

<img width="886" alt="abe" src="https://user-images.githubusercontent.com/34572218/90123022-cc81dc80-dd7b-11ea-9e3c-e5b7208ab278.png">

**Comment by rpaquay** [comment]
This is problably because you are running windows in "hidpi" mode. Can you try setting "Change size of app and text" To 100% in the "Display Settings" of your Windows and see if this fixed the problem.

**Comment by BalarajAdappa** [comment]
@rpaquay thanks for your help, after i change display setting and its working fine now,
